---
- name: Install postfix
  hosts: localhost
  become: yes

  gather_facts: no
  tasks:
  - name: install postfix
    apt:
      name: postfix
      state: present
    tags: init postfix  

  - name: remove postfix
    apt:
      name: postfix
      state: absent
    tags: drop postfix